//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtjsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ext_Tree
    {
        public int id { get; set; }
        public Nullable<int> rid { get; set; }
        public Nullable<int> parentId { get; set; }
        public string text { get; set; }
        public string index { get; set; }
        public Nullable<bool> expanded { get; set; }
        public Nullable<bool> leaf { get; set; }
        public Nullable<bool> root { get; set; }
        public string href { get; set; }
        public string qtitle { get; set; }
        public string qtip { get; set; }
    }
}
